In [2]:
#Matrix Addition using list

#Create two matrices
A=[[1, 2, 3],
   [4, 5, 6]]

B=[[7, 8, 9],
   [10, 11, 12]]

#Create an empty matrix C
C=[[0, 0, 0],
   [0, 0, 0]]

#Add corresponding elements
for i in range(len(A)):
    for j in range(len(A[0])):
        C[i][j]=A[i][j]+B[i][j]

#Display matrices
print("Matrix A:")
for row in A:
    print(row)

print("Matrix B:")
for row in B:
    print(row)

print("Matrix C (A+B):")
for row in C:
    print(row)

Matrix A:
[1, 2, 3]
[4, 5, 6]
Matrix B:
[7, 8, 9]
[10, 11, 12]
Matrix C (A+B):
[8, 10, 12]
[14, 16, 18]


In [3]:
#Matrix Addition using NumPy

import numpy as np

#Create NumPy arrays
A=np.array([[1, 2, 3],
            [4, 5, 6]])

B=np.array([[7, 8, 9],
            [10, 11, 12]])

#Add matrices
C=A+B

#Display matrices
print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Matrix C (A+B):")
print(C)

Matrix A:
[[1 2 3]
 [4 5 6]]
Matrix B:
[[ 7  8  9]
 [10 11 12]]
Matrix C (A+B):
[[ 8 10 12]
 [14 16 18]]
